---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  eslint:
    enabled: true
    channel: eslint-3
  fixme:
    enabled: true
ratings:
  paths:
  - "examples/*.js"
  - "lib/*.js"
  - "lib/sync/*.js"
