language: node_js

node_js:
  - "0.10"
  - "0.11"
  - "0.12"

addons:
  postgresql: "9.3"

before_script:
  - echo 'UTC' | sudo tee /etc/timezone
  - sudo dpkg-reconfigure --frontend noninteractive tzdata
  - psql -c "CREATE DATABASE pgo;" -U postgres
  - psql -c "ALTER DATABASE pgo SET timezone TO 'GMT';" -U postgres
