language: node_js

node_js:
  - "0.10"
  - "0.11"
  - "0.12"
  - "4.0"

env:
  matrix:
    - PG_VERSION=9.1
    - PG_VERSION=9.2
    - PG_VERSION=9.3
    - PG_VERSION=9.4

addons:
  postgresql: `echo $PG_VERSION`
  code_climate:
    repo_token: e3c49594443b1f9bcaf2e85f560bc6aee56ce61bb2b824b052dc1a1765e93bb6

before_script:
  - psql -c "CREATE DATABASE pgo;" -U postgres
  - psql -c "ALTER DATABASE pgo SET timezone TO 'GMT';" -U postgres
  - export PGO_TEST_DB="postgres://postgres@localhost/pgo"

after_script:
  - npm install codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
