language: node_js

node_js:
  - "0.10"
  - "0.11"
  - "0.12"

addons:
  postgresql: "9.3"

before_script:
  - psql -c "CREATE DATABASE pgo;" -U postgres
  - psql -c "ALTER DATABASE pgo SET timezone TO 'GMT';" -U postgres
  - export PGO_TEST_DB="postgres://postgres@localhost/pgo"
